language: node_js
node_js:
  - "lts/*"
script:
  - "npm run sui:build"
  - "npm run build"
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local-dir: public
  on:
    branch: master