language: node_js
node_js:
  - "lts/*"
cache: yarn
script:
  - "npm run sui:build"
  - "npm run build"
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local-dir: public
  repo: moscow-freecodecamp/moscow-freecodecamp.github.io
  on:
    branch: master